name: CI/CD Docker image 

on:
  push:
    branches:
      - master
      
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up Dcoker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
<<<<<<< HEAD
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Set image URI
      #   id: set-image-uri
      #   run: |
      #     IMAGE_URI="${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
      #     echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      #     echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      


      # - name: Login to Docker HUB
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Build and Push Docker image 
      #   uses: docker/build-push-action@v4
      #   with:
      #     Context: .
      #     push: true
      #     tags: rbaviskar777/myapp:latest 
=======
          Context: .
          push: true
          tags: rbaviskar777/myapp:latest 
>>>>>>> 180e4c0c78daebd402d1a5d0ba63247e29538916
         
