name: CI/CD Docker image 

on:
  push:
    branches:
      - master
      
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up Dcoker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: C:\Users\RohitBhanudasBaviska\OneDrive - ValueMomentum, Inc\Desktop\my-docker-app\Dockerfile            # path to your Dockerfile; keep lowercase
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .            # path to your Dockerfile
      #     push: true
      #     tags: |
      #       ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      # # - name: Set image URI
      # #   id: set-image-uri
      # #   run: |
      # #     IMAGE_URI="${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
      # #     echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      # #     echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      


      # # - name: Login to Docker HUB
      # #   uses: docker/login-action@v3
      # #   with:
      # #     username: ${{ secrets.DOCKER_USERNAME }}
      # #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # # - name: Build and Push Docker image 
      # #   uses: docker/build-push-action@v4
      # #   with:
      # #     Context: .
      # #     push: true
      # #     tags: rbaviskar777/myapp:latest 

         
