
name: Test SSH Connection

on: workflow_dispatch

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      # - name: Copy SSH key
      #   run: |
      #     echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
      #     chmod 600 key.pem

      - name: Test SSH
        run: |
